-- Supabase / PostgreSQL schema for the current POS and Inventory backend.
-- This schema is based on:
-- 1) backend/pos_and_inventory_system.sql
-- 2) newer migration SQL files in backend/
-- 3) runtime table usage in backend/src/controllers and backend/src/socket
--
-- Notes:
-- - This file targets PostgreSQL 15+ as used by Supabase.
-- - It creates schema only, not application data.
-- - Several tables/columns here reflect the current backend code, even when the
--   legacy MySQL dump is older or inconsistent.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.ifnull(a anycompatible, b anycompatible)
returns anycompatible
language sql
immutable
as $$
  select coalesce(a, b)
$$;

create or replace function public.curdate()
returns date
language sql
stable
as $$
  select current_date
$$;

create or replace function public.rand()
returns double precision
language sql
volatile
as $$
  select random()
$$;

create or replace function public.year(value timestamptz)
returns integer
language sql
immutable
as $$
  select extract(year from value)::integer
$$;

create or replace function public.month(value timestamptz)
returns integer
language sql
immutable
as $$
  select extract(month from value)::integer
$$;

create or replace function public.quarter(value timestamptz)
returns integer
language sql
immutable
as $$
  select extract(quarter from value)::integer
$$;

create or replace function public.week(value timestamptz, mode integer default 0)
returns integer
language sql
immutable
as $$
  select case
    when mode = 1 then to_char(value, 'IW')::integer
    else extract(week from value)::integer
  end
$$;

create or replace function public.date_format(value timestamptz, format_text text)
returns text
language sql
immutable
as $$
  select to_char(
    value,
    replace(
      replace(
        replace(
          replace(
            replace(format_text, '%Y', 'YYYY'),
            '%m', 'MM'
          ),
          '%d', 'DD'
        ),
        '%H', 'HH24'
      ),
      '%i', 'MI'
    )
  )
$$;

create or replace function public.convert_tz(value timestamptz, from_tz text, to_tz text)
returns timestamp
language sql
stable
as $$
  select timezone(to_tz, value)
$$;

create or replace function public.timestampdiff(unit_name text, start_value timestamptz, end_value timestamptz)
returns bigint
language sql
immutable
as $$
  select case upper(unit_name)
    when 'MINUTE' then floor(extract(epoch from (end_value - start_value)) / 60)::bigint
    when 'HOUR' then floor(extract(epoch from (end_value - start_value)) / 3600)::bigint
    when 'DAY' then floor(extract(epoch from (end_value - start_value)) / 86400)::bigint
    else floor(extract(epoch from (end_value - start_value)))::bigint
  end
$$;

create table if not exists public.roles (
  role_id integer generated by default as identity primary key,
  role_name varchar(255) not null unique
);

create table if not exists public.branches (
  branch_id integer generated by default as identity primary key,
  branch_name varchar(100) not null,
  address text not null,
  contact_number varchar(20) not null,
  opening_time time not null,
  closing_time time not null,
  status text not null default 'Active' check (status in ('Active', 'Closed', 'Suspended')),
  created_by integer,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.categories (
  category_id integer generated by default as identity primary key,
  category_name varchar(255) not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.users (
  user_id integer generated by default as identity primary key,
  full_name varchar(255) not null,
  first_name varchar(100),
  last_name varchar(100),
  username varchar(100) not null unique,
  password varchar(255) not null,
  role_id integer not null references public.roles(role_id),
  created_by integer,
  status text not null default 'Activate' check (status in ('Activate', 'Deactivate')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  branch_id integer references public.branches(branch_id),
  contact_number varchar(20),
  pin_code varchar(10),
  constraint users_created_by_fkey
    foreign key (created_by) references public.users(user_id) on delete set null
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'branches_created_by_fkey'
  ) then
    alter table public.branches
      add constraint branches_created_by_fkey
      foreign key (created_by) references public.users(user_id) on delete set null;
  end if;
end;
$$;

create table if not exists public.portions (
  portion_id integer generated by default as identity primary key,
  portion_name varchar(100) not null,
  unit varchar(10),
  formula_json jsonb not null
);

create table if not exists public.inventory (
  inventory_id integer generated by default as identity primary key,
  branch_id integer not null references public.branches(branch_id) on delete cascade,
  item_name varchar(255) not null,
  quantity numeric(10,2) not null default 0,
  servings_per_unit numeric(10,2) not null default 1,
  total_servings numeric(10,2) not null default 0,
  low_stock_threshold numeric(10,2) not null default 10,
  status text not null default 'available' check (status in ('available', 'low_stock', 'out_of_stock', 'unavailable')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  product_id integer generated by default as identity primary key,
  created_by integer not null references public.users(user_id) on delete cascade,
  branch_id integer not null references public.branches(branch_id) on delete cascade,
  product_name varchar(255) not null,
  category_id integer not null references public.categories(category_id) on delete cascade,
  price numeric(10,2) not null default 0,
  image_name varchar(255),
  image_path varchar(255),
  status text not null default 'available' check (status in ('available', 'unavailable')),
  menu_status text not null default 'active' check (menu_status in ('active', 'archived')),
  approval_status text not null default 'PENDING' check (approval_status in ('PENDING', 'APPROVED', 'DECLINED')),
  reviewed_by integer references public.users(user_id) on delete set null,
  reviewed_at timestamptz,
  decline_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.menu_inventory (
  product_id integer not null references public.products(product_id) on delete cascade,
  inventory_id integer not null references public.inventory(inventory_id) on delete cascade,
  servings_required numeric(10,3) not null default 0,
  primary key (product_id, inventory_id)
);

create table if not exists public.menu_item_portions (
  product_id integer not null references public.products(product_id) on delete cascade,
  portion_id integer not null references public.portions(portion_id) on delete cascade,
  qty numeric(10,3) not null default 1.000,
  primary key (product_id, portion_id)
);

create table if not exists public.chat_rooms (
  room_id integer generated by default as identity primary key,
  room_name varchar(255) not null,
  room_type text not null default 'branch' check (room_type in ('branch', 'private')),
  branch_id integer references public.branches(branch_id) on delete cascade,
  created_by integer references public.users(user_id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists chat_rooms_branch_unique
  on public.chat_rooms(branch_id)
  where room_type = 'branch' and branch_id is not null;

create table if not exists public.chat_room_members (
  id integer generated by default as identity primary key,
  room_id integer not null references public.chat_rooms(room_id) on delete cascade,
  user_id integer not null references public.users(user_id) on delete cascade,
  joined_at timestamptz not null default timezone('utc', now()),
  unique (room_id, user_id)
);

create table if not exists public.messages (
  message_id integer generated by default as identity primary key,
  room_id integer not null references public.chat_rooms(room_id) on delete cascade,
  sender_id integer not null references public.users(user_id) on delete cascade,
  message text not null default '',
  message_type text not null default 'text' check (message_type in ('text', 'image', 'file')),
  attachment_url text,
  attachment_name varchar(255),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.message_status (
  id integer generated by default as identity primary key,
  message_id integer not null references public.messages(message_id) on delete cascade,
  user_id integer not null references public.users(user_id) on delete cascade,
  status text not null default 'sent' check (status in ('sent', 'delivered', 'seen')),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (message_id, user_id)
);

create table if not exists public.orders (
  order_id integer generated by default as identity primary key,
  order_date timestamptz not null default timezone('utc', now()),
  total_amount numeric(10,2) not null
);

create table if not exists public.order_items (
  order_item_id integer generated by default as identity primary key,
  order_id integer not null references public.orders(order_id) on delete cascade,
  product_id integer not null references public.products(product_id) on delete cascade,
  quantity integer not null default 1
);

create table if not exists public.transactions (
  transaction_id integer generated by default as identity primary key,
  transaction_number varchar(50) not null unique,
  subtotal numeric(10,2) not null default 0,
  discount_type varchar(50) not null default 'none',
  discount_value numeric(10,2) not null default 0,
  discount_amount numeric(10,2) not null default 0,
  total_amount numeric(10,2) not null default 0,
  payment_method varchar(50) not null,
  amount_paid numeric(10,2) not null default 0,
  change_amount numeric(10,2) not null default 0,
  cashier_id integer not null references public.users(user_id),
  branch_id integer not null references public.branches(branch_id),
  status text not null default 'Completed' check (status in ('Completed', 'Partial Refunded', 'Refunded', 'Voided', 'Partial Voided')),
  order_type varchar(20) not null default 'dine-in' check (order_type in ('dine-in', 'takeout')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.transaction_items (
  transaction_item_id integer generated by default as identity primary key,
  transaction_id integer not null references public.transactions(transaction_id) on delete cascade,
  menu_id integer not null references public.products(product_id) on delete restrict,
  quantity integer not null default 0,
  price numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  voided_quantity integer not null default 0,
  refunded_qty integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.voids (
  void_id integer generated by default as identity primary key,
  transaction_id integer not null references public.transactions(transaction_id) on delete cascade,
  cashier_id integer not null references public.users(user_id),
  manager_id integer not null references public.users(user_id),
  branch_id integer not null references public.branches(branch_id),
  reason text not null,
  void_time timestamptz not null default timezone('utc', now())
);

create table if not exists public.refunds (
  refund_id integer generated by default as identity primary key,
  transaction_id integer not null references public.transactions(transaction_id) on delete cascade,
  manager_id integer not null references public.users(user_id),
  branch_id integer not null references public.branches(branch_id),
  refund_amount numeric(10,2) not null default 0,
  reason text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.transaction_logs (
  transaction_log_id integer generated by default as identity primary key,
  transaction_id integer not null references public.transactions(transaction_id) on delete cascade,
  action varchar(100) not null,
  performed_by integer references public.users(user_id) on delete set null,
  reason text,
  details text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activity_logs (
  log_id integer generated by default as identity primary key,
  user_id integer references public.users(user_id) on delete set null,
  branch_id integer references public.branches(branch_id) on delete set null,
  activity_type varchar(100) not null,
  reference_id integer,
  description text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.login_logs (
  login_log_id integer generated by default as identity primary key,
  user_id integer references public.users(user_id) on delete set null,
  branch_id integer references public.branches(branch_id) on delete set null,
  username_attempted varchar(100) not null,
  status text not null check (status in ('SUCCESS', 'FAILED')),
  reason text,
  ip_address varchar(255),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.raw_items (
  raw_item_id integer generated by default as identity primary key,
  name varchar(100) not null,
  unit varchar(10) not null,
  quantity numeric(10,2),
  supplier varchar(255),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.account_recovery (
  user_id integer primary key references public.users(user_id) on delete cascade,
  recovery_pin_hash varchar(255) not null
);

create table if not exists public.password_reset_tokens (
  pass_reset_token_id integer generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade,
  token_hash varchar(255) not null,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.recovery_attempts (
  recovery_attempt_id integer generated by default as identity primary key,
  user_id integer not null unique references public.users(user_id) on delete cascade,
  failed_attempts integer not null default 0,
  lock_until timestamptz,
  last_attempt_at timestamptz
);

create index if not exists idx_inventory_branch_id on public.inventory(branch_id);
create index if not exists idx_inventory_status on public.inventory(status);
create index if not exists idx_products_branch_id on public.products(branch_id);
create index if not exists idx_products_created_by on public.products(created_by);
create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_products_reviewed_by on public.products(reviewed_by);
create index if not exists idx_chat_room_members_user_id on public.chat_room_members(user_id);
create index if not exists idx_messages_room_created_at on public.messages(room_id, created_at desc);
create index if not exists idx_messages_sender_id on public.messages(sender_id);
create index if not exists idx_message_status_user_id on public.message_status(user_id);
create index if not exists idx_users_role_id on public.users(role_id);
create index if not exists idx_users_branch_id on public.users(branch_id);
create index if not exists idx_users_created_by on public.users(created_by);
create index if not exists idx_activity_logs_user_id on public.activity_logs(user_id);
create index if not exists idx_activity_logs_branch_id on public.activity_logs(branch_id);
create index if not exists idx_activity_logs_type on public.activity_logs(activity_type);
create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);
create index if not exists idx_login_logs_branch_id on public.login_logs(branch_id);
create index if not exists idx_login_logs_status on public.login_logs(status);
create index if not exists idx_login_logs_created_at on public.login_logs(created_at desc);
create index if not exists idx_transactions_branch_status_created on public.transactions(branch_id, status, created_at desc);
create index if not exists idx_transactions_cashier_id on public.transactions(cashier_id);
create index if not exists idx_transaction_items_transaction_id on public.transaction_items(transaction_id);
create index if not exists idx_transaction_items_menu_id on public.transaction_items(menu_id);
create index if not exists idx_voids_branch_time on public.voids(branch_id, void_time desc);
create index if not exists idx_refunds_branch_created on public.refunds(branch_id, created_at desc);
create index if not exists idx_password_reset_tokens_token_hash on public.password_reset_tokens(token_hash);

drop trigger if exists trg_branches_updated_at on public.branches;
create trigger trg_branches_updated_at
before update on public.branches
for each row execute function public.set_updated_at();

drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_inventory_updated_at on public.inventory;
create trigger trg_inventory_updated_at
before update on public.inventory
for each row execute function public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_message_status_updated_at on public.message_status;
create trigger trg_message_status_updated_at
before update on public.message_status
for each row execute function public.set_updated_at();

drop trigger if exists trg_transactions_updated_at on public.transactions;
create trigger trg_transactions_updated_at
before update on public.transactions
for each row execute function public.set_updated_at();

insert into public.roles (role_id, role_name)
values
  (1, 'Cashier'),
  (2, 'Admin'),
  (3, 'SuperAdmin')
on conflict (role_id) do update
set role_name = excluded.role_name;

select setval(
  pg_get_serial_sequence('public.roles', 'role_id'),
  coalesce((select max(role_id) from public.roles), 1),
  true
);

commit;